### ISSUE TITLE
fly launch with Phoenix app and provisioned Postgres fails

### ISSUE THREAD

**Issue by PJUllrich** [superfly/flyctl#1612]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

I created a new phoenix app and ran `fly launch` for it. I provided it with a Postgres instance, but the very first deploy crashed. I set the `DATABASE_URL` manually, but any subsequent `fly launch` also crashes because it can't parse the `DATABASE_URL` which I simply copy&pasted into the secrets.

* Operating system
* macOS 13.0.1
* `fly version`
* First: 0.0.443, Then updated to 0.0.450 but still the same problem.

> I replaced my fly app name with `APP_NAME` and my phoenix app name with simply `APP`

** Paste your `fly.toml`

```toml
# fly.toml file generated for APP_NAME on 2023-01-22T21:35:39+01:00

app = "APP_NAME"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "APP_NAME.fly.dev"
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

```text
➜  APP_NAME git:(main) fly launch
Update available 0.0.443 -> 0.0.450.
Run "fly version update" to upgrade.
Creating app in /Users/peterullrich/Development/APP_NAME
Scanning source code
Resolving Hex dependencies...
Resolution completed in 0.171s
Unchanged:
  castore 1.0.0
  connection 1.1.0
  cowboy 2.9.0
  cowboy_telemetry 0.4.0
  cowlib 2.11.0
  db_connection 2.4.3
  decimal 2.0.0
  ecto 3.9.4
  ecto_sql 3.9.2
  esbuild 0.6.0
  expo 0.3.0
  file_system 0.2.10
  floki 0.34.0
  gettext 0.22.0
  jason 1.4.0
  mime 2.0.3
  phoenix 1.6.15
  phoenix_ecto 4.4.0
  phoenix_html 3.2.0
  phoenix_live_dashboard 0.6.5
  phoenix_live_reload 1.4.1
  phoenix_live_view 0.17.12
  phoenix_pubsub 2.1.1
  phoenix_template 1.0.0
  phoenix_view 2.0.2
  plug 1.14.0
  plug_cowboy 2.6.0
  plug_crypto 1.2.3
  postgrex 0.16.5
  ranch 1.8.0
  swoosh 1.9.1
  telemetry 1.2.1
  telemetry_metrics 0.6.1
  telemetry_poller 1.0.0
All dependencies are up to date
Detected a Phoenix app
? Create .dockerignore from 2 .gitignore files? Yes
Created /Users/peterullrich/Development/APP_NAME/.dockerignore from 2 .gitignore files.
? Choose an app name (leave blank to generate one): APP_NAME
automatically selected personal organization: Peter Ullrich
? Choose a region for deployment: Amsterdam, Netherlands (ams)
Created app APP_NAME in organization personal
Admin URL: https://fly.io/apps/APP_NAME
Hostname: APP_NAME.fly.dev
Set secrets on APP_NAME: SECRET_KEY_BASE
Preparing system for Elixir builds
Installing application dependencies
Running Docker release generator
Wrote config file fly.toml
? Would you like to set up a Postgresql database now? Yes
? Select configuration: Development - Single node, 1x shared CPU, 256MB RAM, 1GB disk
Creating postgres cluster in organization personal
Creating app...
Setting secrets on app APP_NAME-db...
Provisioning 1 of 1 machines with image flyio/postgres:14.6
Waiting for machine to start...
Machine 4d89623b56e987 is created
==> Monitoring health checks

Postgres cluster APP_NAME-db created
  Username:    postgres
  Password:    PASSWORD_HERE
  Hostname:   APP_NAME-db
  Proxy port:  5432
  Postgres port:  5433
  Connection string: postgres://postgres:PASSWORD@APP_NAME-db:5432

Save your credentials in a secure place -- you won't be able to see them again!

Connect to postgres
Any app within the Peter Ullrich organization can connect to this Postgres using the above connection string

Now that you've set up Postgres, here's what you need to understand: https://fly.io/docs/postgres/getting-started/what-you-should-know/
Failed attaching APP_NAME to the Postgres cluster APP_NAME-db: %!w(*fmt.wrapError=&{machines could not be retrieved failed to list VMs: request returned non-2xx status, 500 0
? Would you like to set up an Upstash Redis database now? No
? Would you like to deploy now? Yes
==> Building image
Remote builder fly-builder-aged-shadow-5467 ready
==> Creating build context
--> Creating build context done
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
Sending build context to Docker daemon  109.2kB
[+] Building 94.9s (28/28) FINISHED                                                                                                                                           
 => [internal] load remote build context                                                                                                                                 0.0s
 => copy /context /                                                                                                                                                      0.1s
 => [internal] load metadata for docker.io/library/debian:bullseye-20220801-slim                                                                                         0.5s
 => [internal] load metadata for docker.io/hexpm/elixir:1.14.2-erlang-25.1.1-debian-bullseye-20220801-slim                                                               0.4s
 => [stage-1 1/6] FROM docker.io/library/debian:bullseye-20220801-slim@sha256:a811e62769a642241b168ac34f615fb02da863307a14c4432cea8e5a0f9782b8                           0.0s
 => CACHED [stage-1 2/6] RUN apt-get update -y && apt-get install -y libstdc++6 openssl libncurses5 locales   && apt-get clean && rm -f /var/lib/apt/lists/*_*           0.0s
 => CACHED [stage-1 3/6] RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen                                                                                0.0s
 => CACHED [stage-1 4/6] WORKDIR /app                                                                                                                                    0.0s
 => CACHED [stage-1 5/6] RUN chown nobody /app                                                                                                                           0.0s
 => CACHED [builder  1/17] FROM docker.io/hexpm/elixir:1.14.2-erlang-25.1.1-debian-bullseye-20220801-slim@sha256:c85c3dd4d09c6966afbdfff628281f3c9920c2c34056167ad137e9  0.0s
 => [builder  2/17] RUN apt-get update -y && apt-get install -y build-essential git     && apt-get clean && rm -f /var/lib/apt/lists/*_*                                28.0s
 => [builder  3/17] WORKDIR /app                                                                                                                                         0.0s
 => [builder  4/17] RUN mix local.hex --force &&     mix local.rebar --force                                                                                             2.6s
 => [builder  5/17] COPY mix.exs mix.lock ./                                                                                                                             0.0s 
 => [builder  6/17] RUN mix deps.get --only prod                                                                                                                         2.5s 
 => [builder  7/17] RUN mkdir config                                                                                                                                     0.3s 
 => [builder  8/17] COPY config/config.exs config/prod.exs config/                                                                                                       0.0s 
 => [builder  9/17] RUN mix deps.compile                                                                                                                                53.0s 
 => [builder 10/17] COPY priv priv                                                                                                                                       0.0s 
 => [builder 11/17] COPY lib lib                                                                                                                                         0.0s 
 => [builder 12/17] COPY assets assets                                                                                                                                   0.0s 
 => [builder 13/17] RUN mix assets.deploy                                                                                                                                3.3s
 => [builder 14/17] RUN mix compile                                                                                                                                      1.4s 
 => [builder 15/17] COPY config/runtime.exs config/                                                                                                                      0.0s 
 => [builder 16/17] COPY rel rel                                                                                                                                         0.0s 
 => [builder 17/17] RUN mix release                                                                                                                                      2.5s 
 => [stage-1 6/6] COPY --from=builder --chown=nobody:root /app/_build/prod/rel/APP_NAME                                                                                  0.2s 
 => exporting to image                                                                                                                                                   0.4s 
 => => exporting layers                                                                                                                                                  0.4s 
 => => writing image sha256:af7d22c6bef99083d2431789504565cfe4f9d4d951ab56245cd130e79f97812e                                                                             0.0s 
 => => naming to registry.fly.io/APP_NAME:deployment-01GQDKMZCDJCPVSTVCRX1SNFHD                                                                                          0.0s
--> Building image done
==> Pushing image to fly
The push refers to repository [registry.fly.io/APP_NAME]
27906154c6bd: Pushed 
1b41803a1bb3: Pushed 
4d17d22e718d: Pushed 
5722307cd34c: Pushed 
297fe24e93e8: Pushed 
92a4e8a3140f: Pushed 
deployment-01GQDKMZCDJCPVSTVCRX1SNFHD: digest: sha256:a206ef0acca609f1babac680872294ddddf3155818c5cced7d9d7006fe933bae size: 1576
--> Pushing image done
image: registry.fly.io/APP_NAME:deployment-01GQDKMZCDJCPVSTVCRX1SNFHD
image size: 124 MB
==> Creating release
--> release v2 created

--> You can detach the terminal anytime without stopping the deployment
==> Release command detected: /app/bin/migrate

--> This release will not be available until the release command succeeds.
         Starting instance
         Configuring virtual machine
         Pulling container image
         Unpacking image
         Preparing kernel init
         Starting virtual machine
         Starting init (commit: b8364bb)...
         Setting up swapspace version 1, size = 512 MiB (536866816 bytes)
         no label, UUID=dede9ea6-1496-4d54-917e-77ba38fdb7d1
         Preparing to run: `/app/bin/migrate` as nobody
         2023/01/22 20:47:22 listening on [fdaa:0:20aa:a7b:23c5:328d:9a87:2]:22 (DNS: [fdaa::3]:53)
         ERROR! Config provider Config.Reader failed with:
         ** (RuntimeError) environment variable DATABASE_URL is missing.
         For example: ecto://USER:PASS@HOST/DATABASE
             /app/releases/0.1.0/runtime.exs:26: (file)
             (elixir 1.14.2) src/elixir.erl:309: anonymous fn/4 in :elixir.eval_external_handler/1
             (stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
             (stdlib 4.1.1) erl_eval.erl:492: :erl_eval.expr/6
             (stdlib 4.1.1) erl_eval.erl:136: :erl_eval.exprs/6
             (elixir 1.14.2) src/elixir.erl:294: :elixir.eval_forms/4
             (elixir 1.14.2) lib/module/parallel_checker.ex:107: Module.ParallelChecker.verify/1
             (elixir 1.14.2) lib/code.ex:425: Code.validated_eval_string/3
         {"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<101,110,118,105,114,111,110,109,101,110,116,32,118,97,114,105,97,98,108,101,32,68,65,84,65,66,65,83,69,95,85,82,76,32,105,115,32,109,105,115,115,105,110,103,46,10,70,111,114,32,101,120,97,109,112,108,101,58,32,101,99,116,111,58,47,47,85,83,69,82,58,80,65,83,83,64,72,79,83,84,47,68,65,84,65,66,65,83,69,10>>},[{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.1.0/runtime.exs"},{line,26}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,309},{error_info,#{module=>'Elixir.Exception'}}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,492}]},{erl_eval,exprs,6,[{file,"erl_eval.erl"},{line,136}]},{elixir,eval_forms,4,[{file,"src/elixir.erl"},{line,294}]},{'Elixir.Module.ParallelChecker',verify,1,[{file,"lib/module/parallel_checker.ex"},{line,107}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,425}]}]}}
         init terminating in do_boot ({,[{elixir_eval,__FILE__,1,[{_},{_}]},{elixir,-eval_external_handler/1-fun-2-,4,[{_},{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,exprs,6,[{_},{_}]},{elixir,eval_forms,4,[{_},{_}]},{Elixir.Module.ParallelChecker,verify,1,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]}]})
         Crash dump is being written to: erl_crash.dump...done
         Starting clean up.
Error release command failed, deployment aborted
```

**Subsequent Deploy**

```text
2023-01-22T20:49:45.299 app[c89cc474] ams [info] Starting init (commit: b8364bb)...
2023-01-22T20:49:45.347 app[c89cc474] ams [info] Setting up swapspace version 1, size = 512 MiB (536866816 bytes)
2023-01-22T20:49:45.348 app[c89cc474] ams [info] no label, UUID=34062ffd-fe02-4931-a12b-93b2b8c259dc
2023-01-22T20:49:45.351 app[c89cc474] ams [info] Preparing to run: `/app/bin/migrate` as nobody
2023-01-22T20:49:45.370 app[c89cc474] ams [info] 2023/01/22 20:49:45 listening on [fdaa:0:20aa:a7b:a356:c89c:c474:2]:22 (DNS: [fdaa::3]:53)
2023-01-22T20:49:47.005 app[c89cc474] ams [info] ** (Ecto.InvalidURLError) invalid url postgres://postgres:PASSWORD@APP_NAME-db.internal:5432, path should be a database name. The parsed URL is: %URI{scheme: "postgres", authority: "postgres:PASSWORD@APP_NAME-db.internal:5432", userinfo: "postgres:PASSWORD", host: "APP_NAME-db.internal", port: 5432, path: nil, query: nil, fragment: nil}
2023-01-22T20:49:47.005 app[c89cc474] ams [info] lib/ecto/repo/supervisor.ex:96: Ecto.Repo.Supervisor.parse_url/1
2023-01-22T20:49:47.005 app[c89cc474] ams [info] lib/ecto/repo/supervisor.ex:28: Ecto.Repo.Supervisor.runtime_config/4
2023-01-22T20:49:47.005 app[c89cc474] ams [info] (APP 0.1.0) lib/APP/repo.ex:2: APP.Repo.config/0
2023-01-22T20:49:47.005 app[c89cc474] ams [info] lib/ecto/migrator.ex:126: Ecto.Migrator.with_repo/3
2023-01-22T20:49:47.005 app[c89cc474] ams [info] (APP 0.1.0) lib/APP/release.ex:12: anonymous fn/2 in APP.Release.migrate/0
2023-01-22T20:49:47.005 app[c89cc474] ams [info] (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
2023-01-22T20:49:47.005 app[c89cc474] ams [info] (APP 0.1.0) lib/APP/release.ex:11: APP.Release.migrate/0
2023-01-22T20:49:47.005 app[c89cc474] ams [info] nofile:1: (file)
2023-01-22T20:49:47.360 app[c89cc474] ams [info] Starting clean up.
```

**Comment by PJUllrich** [comment]
After the initial deploy failed, I tried to set the database URL with the connection string from the launch output like this:

```
fly secrets set DATABASE_URL="postgres://postgres:PASSWORD@APP_NAME-db:5432"
```

You'll notice that the path is missing from that URL, so that's why the second deploy failed. Now, I'm trying to figure out which path I should use there.

**Comment by catflydotio** [comment]
Try `fly secrets set DATABASE_URL="postgres://postgres:PASSWORD@APP_NAME-db.internal:5432"`?

I don't think there's a bug, so I'm closing.

**Comment by PJUllrich** [comment]
@catflydotio I'm sorry. I did exactly as you suggested but that led to the second error message. (I missed the `.internal` part in my second message, but I added that part in my `DATABASE_URL` as you can see in the second error message.

However, the `path` was missing from the `DATABASE_URL` which I took from the `Connection String`, as is shown in this error message of the subsequent deploy:

```text
** (Ecto.InvalidURLError) invalid url postgres://postgres:PASSWORD@APP_NAME-db.internal:5432, path should be a database name. The parsed URL is: %URI{scheme: "postgres", authority: "postgres:PASSWORD@APP_NAME-db.internal:5432", userinfo: "postgres:PASSWORD", host: "APP_NAME-db.internal", port: 5432, path: nil, query: nil, fragment: nil}
```

What should the `path` be in this situation?

May I suggest that you add the correct path to the `Connection string` which is printed after deploying the Postgres instance? 

Also, if I use Fly's `launch` command and it asks me whether it should provide a database for me and I say `Yes`, I'd expect it to not crash and execute the deploy successfully. That's why I labeled this as a `bug`.

**Comment by catflydotio** [comment]
Something definitely went wrong during your launch:

```
Failed attaching APP_NAME to the Postgres cluster APP_NAME-db: %!w(*fmt.wrapError=&{machines could not be retrieved failed to list VMs: request returned non-2xx status, 500 0
```
I am guessing that was a transient error. That's definitely not the experience we want you to have. The point is, of course, that attaching the app should allow you to skip thinking about the connection string on launch. I don't *think* this error is related to the connection string, though.

Within your Fly.io [private network](https://fly.io/docs/reference/private-networking), our internal DNS will resolve `APP_NAME-db.internal`.

I'm confident in the connection string itself: I've just provisioned a new app with a new PG cluster and checked that copy-pasting from the output lets me connect psql from within my app's private network.

I'd be tempted to delete the app (and the Postgres app, if it doesn't have data in it), and try launching afresh, with a new PG cluster.

If the "attaching" step goes through OK but Ecto's not happy, there may be project-specific things to do, about which you'll find more expertise (and maybe an existing answer) [in our community forum](https://community.fly.io/)

(Incidentally,  you've mentioned running `fly launch` multiple times. Just to be sure: `fly launch` is for creating and configuring a new app. Once the app exists, you can use `fly deploy`.)
