### ISSUE TITLE
Launching a rails app without a `config/master.key` or `config/credentials/production.key` fails

### ISSUE THREAD

**Issue by bradgessler** [superfly/flyctl#1651]
When I deploy a Rails application without a `config/master.key` or `config/credentials/production.key`, I get the following error:

```
2023-02-01T22:49:40Z   [info]=> Booting Puma
2023-02-01T22:49:40Z   [info]=> Rails 7.0.4.2 application starting in production
2023-02-01T22:49:40Z   [info]=> Run `bin/rails server --help` for more startup options
2023-02-01T22:49:40Z   [info]DEPRECATION WARNING: `with_slot` is deprecated and will be removed in ViewComponent v3.0.0.
2023-02-01T22:49:40Z   [info]Use the new slots API (https://viewcomponent.org/guide/slots.html) instead. (called from <class:ItemListCardComponent> at /rails/app/components/item_list_card_component.rb:5)
2023-02-01T22:49:40Z   [info]DEPRECATION WARNING: `with_slot` is deprecated and will be removed in ViewComponent v3.0.0.
2023-02-01T22:49:40Z   [info]Use the new slots API (https://viewcomponent.org/guide/slots.html) instead. (called from <class:ListCardComponent> at /rails/app/components/list_card_component.rb:4)
2023-02-01T22:49:40Z   [info]DEPRECATION WARNING: `with_slot` is deprecated and will be removed in ViewComponent v3.0.0.
2023-02-01T22:49:40Z   [info]Use the new slots API (https://viewcomponent.org/guide/slots.html) instead. (called from <class:ListCardComponent> at /rails/app/components/list_card_component.rb:5)
2023-02-01T22:49:40Z   [info]DEPRECATION WARNING: `with_slot` is deprecated and will be removed in ViewComponent v3.0.0.
2023-02-01T22:49:40Z   [info]Use the new slots API (https://viewcomponent.org/guide/slots.html) instead. (called from <class:MenuComponent> at /rails/app/components/menu_component.rb:4)
2023-02-01T22:49:41Z   [info]Exiting
2023-02-01T22:49:41Z   [info]/rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/application.rb:581:in `validate_secret_key_base': Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)
2023-02-01T22:49:41Z   [info]        raise ArgumentError, "Missing `secret_key_base` for '#{Rails.env}' environment, set this string with `bin/rails credentials:edit`"
2023-02-01T22:49:41Z   [info]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-01T22:49:41Z   [info]	from /rails/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.2/lib/rails/application.rb:419:in `secret_key_base'
2023-02-01T22:49:42Z   [info]Starting clean up.
--> v0 failed - Failed due to unhealthy allocations - no stable job version to auto revert to and deploying as v1

--> Troubleshooting guide at https://fly.io/docs/getting-started/troubleshooting/
Error abort
```

This is caused by the code below not resolving a secret key base if it can't find it in a credentials file.

https://github.com/superfly/flyctl/blob/1e7e28d6999f5f2ba154d5b168da1aa34c96df4e/scanner/rails.go#L24-L41

> All rails apps since 5.2 use the secret_key_base from the encrypt credential file

In my case, the Rails application started at version 5.1. I've since upgraded it to Rails 7.x, but I never bothered to generate the encrypted configuration files since I only configure via ENV vars.

In this quick poll I ran on Twitter, about half the people that responded configure via ENV vars (https://twitter.com/bradgessler/status/1620522549326266368?s=61&t=4IfPTFM3Rh9v9QrGNufixA)

## Proposal

If the secret key base can't be resolved from the `.key` files, prompt the user that the file could not be found and give the option to create a `SECRET_KEY_BASE` fly secret for them. The secret could be generated on the users machine via `rake secret` or `rails secret` to be functionally equivalent to `fly secret set SECRET_KEY_BASE=$(rails secret)`

The user may NOT want to automatically generate this env var if they checked out this repo and forgot to put the secret in their repo. Ideally the error message suggests this could be a problem in addition to giving them the option to generate a secret key base.

**Comment by rubys** [comment]
> prompt the user that the file could not be found and give the option to create a SECRET_KEY_BASE fly secret for them.

I'm inclined to skip the prompt and just set SECRET_KEY_BASE.  It is one less thing for them to worry about, it likely is going to solve their problem, and if not, they are no worse.
