### ISSUE TITLE
panic: close of closed channel, goroutine error.

### ISSUE THREAD

**Issue by Ppang0405** [superfly/flyctl#1953]
I try to deploy python FastAPI app to Fly io and got goroutine error.

* MacOS
* fly v0.0.499 darwin/arm64 Commit: 10c95df6 BuildDate: 2023-03-24T04:50:43Z

** Paste your `fly.toml`

```toml
# fly.toml file generated for snowy-morning-6912 on 2023-03-25T19:27:29+07:00

app = "snowy-morning-6912"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```

** Command output: **

```text

==> Verifying app config
--> Verified app config
==> Building image
Remote builder fly-builder-rough-wave-3915 ready
panic: close of closed channel

goroutine 93 [running]:
github.com/superfly/flyctl/internal/build/imgsrc.(*Resolver).StartHeartbeat.func2()
        github.com/superfly/flyctl/internal/build/imgsrc/resolver.go:507 +0x25c
created by github.com/superfly/flyctl/internal/build/imgsrc.(*Resolver).StartHeartbeat
        github.com/superfly/flyctl/internal/build/imgsrc/resolver.go:501 +0x548
```

**Comment by alichay** [comment]
Sorry about that! A fix is in the works, thanks for reporting this
