### ISSUE TITLE
Panic in runDeploy at ValidateConfig

### ISSUE THREAD

**Issue by tqbf** [superfly/flyctl#213]
From the looks of it: ValidateConfig can return nil error and nil AppConfig --- though that's weird, since ValidateConfig is returning apiClient.ParseConfig, which itself returns a pointer to a stack variable. Anyways: looks like the server hiccuped, and we just showed a stack trace instead of an error.

```runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x1c48620, 0xc0000ce008, 0xc0005f3388)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
main.main.func1()
	/Users/tqbf/codebase/fly/flyctl/main.go:35 +0x1bc
panic(0x19bf7c0, 0x22aeab0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/superfly/flyctl/cmd.runDeploy(0xc0001ea820, 0x0, 0x0)
	/Users/tqbf/codebase/fly/flyctl/cmd/deploy.go:80 +0x1f6
github.com/superfly/flyctl/cmd.BuildCommand.func1(0xc0001b6f00, 0x22e2eb0, 0x0, 0x0)
	/Users/tqbf/codebase/fly/flyctl/cmd/command.go:272 +0x24f
github.com/spf13/cobra.(*Command).execute(0xc0001b6f00, 0x22e2eb0, 0x0, 0x0, 0xc0001b6f00, 0x22e2eb0)
	/Users/tqbf/codebase/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x22b9440, 0x0, 0x0, 0x0)
	/Users/tqbf/codebase/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/tqbf/codebase/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/superfly/flyctl/cmd.Execute()
	/Users/tqbf/codebase/fly/flyctl/cmd/root.go:40 +0x66
main.main()
	/Users/tqbf/codebase/fly/flyctl/main.go:40 +0x1c3
```

**Comment by codepope** [comment]
@tqbf do you have a fly.toml to go with this?
