### ISSUE TITLE
fly launch panic: nested instrument span!

### ISSUE THREAD

**Issue by eexit** [superfly/flyctl#2236]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**

When trying to launch a new app from [this guide](https://fly.io/blog/shipping-logs/), I'm having a go panic error:

```
$ fly launch --image ghcr.io/superfly/fly-log-shipper:latest
```

Runtime info:

```
$ go version
go version go1.20.4 darwin/arm64

$ fly version
fly v0.0.554 darwin/arm64 Commit: aa9b9ad3 BuildDate: 2023-05-05T03:45:30Z

$ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 16 GB
```

** Paste your `fly.toml`

```toml
N/A
```

** Command output: **

```text
Creating app in /Users/{path}/logshippper
Using image ghcr.io/superfly/fly-log-shipper:latest
? Choose an app name (leave blank to generate one):
? Select Organization: blog.eexit.net (blog-eexit-net)
panic: nested instrument span!

goroutine 8 [running]:
github.com/superfly/flyctl/internal/instrument.(*ApiInstrumenter).Begin(0x12ca48c18?)
	github.com/superfly/flyctl/internal/instrument/call.go:61 +0xd0
github.com/superfly/flyctl/api.(*Client).RunWithContext(_, {_, _}, _)
	github.com/superfly/flyctl/api@v0.0.0-20220708073423-b6d7c3cf5161/client.go:121 +0x6c
github.com/superfly/flyctl/api.(*Client).GetOrganizationBySlug(0x140009c6b40?, {0x1044e0ca8, 0x14000a04330}, {0x140008d79c0, 0xe})
	github.com/superfly/flyctl/api@v0.0.0-20220708073423-b6d7c3cf5161/resource_organizations.go:77 +0x164
github.com/superfly/flyctl/internal/build/imgsrc.EagerlyEnsureRemoteBuilder({0x1044e0ca8, 0x14000a04330}, 0x14000b64ba0?, {0x140008d79c0, 0xe})
	github.com/superfly/flyctl/internal/build/imgsrc/docker.go:484 +0x50
created by github.com/superfly/flyctl/internal/command/launch.run
	github.com/superfly/flyctl/internal/command/launch/launch.go:166 +0x604
zsh: exit 2     fly launch --image ghcr.io/superfly/fly-log-shipper:latest
```

**Comment by smorimoto** [comment]
I'm experiencing the same thing now 🥲

**Comment by smorimoto** [comment]
The latest version appears to fix the bug. The upstream repository updates more slowly than the brew tap, so you should be able to use the latest version by just using Fly's brew tap.

```
brew uninstall flyctl
brew tap superfly/homebrew-tap
brew install superfly/tap/flyctl
```

**Comment by eexit** [comment]
> brew uninstall flyctl
brew tap superfly/homebrew-tap
brew install superfly/tap/flyctl

This worked, In was able to deploy my logshipper 🎉 !

Thanks @smorimoto

**Comment by smorimoto** [comment]
Glad to hear that! 😉
