### ISSUE TITLE
`fly deploy` crashes with a ridiculously narrow terminal

### ISSUE THREAD

**Issue by catflydotio** [superfly/flyctl#2474]
I've only seen this (but it's seemingly reproducible) when I've slid the divider between two VS Code terminal panes way over during a deploy so I can watch logs.

```
13:17:01 *[main][~/Projects/CorrosionDemo/corrodemo]$ fly deploy
==> Verifying app config
Validating /Users/chris/Projects/CorrosionDemo/corrodemo/fly.toml
Platform: machines
✓ Configuration is valid
Remote builder fly-builder-solitary-sun-594 ready
==> Creating build context
--> Creating build context done
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
panic: runtime error: makeslice: len out of range

goroutine 102 [running]:
github.com/tonistiigi/vt100.NewVT100(0x6, 0xfffffffffffffffd)
      /home/runner/go/pkg/mod/github.com/tonistiigi/vt100@v0.0.0-20210615222946-8066bb97264f/vt100.go:160 +0x138
github.com/moby/buildkit/util/progress/progressui.(*trace).update(0x14000cb9ea0, 0x14000bad180, 0x7)
      /home/runner/go/pkg/mod/github.com/moby/buildkit@v0.9.0/util/progress/progressui/display.go:222 +0x19c
github.com/moby/buildkit/util/progress/progressui.DisplaySolveStatus({0x104159398, 0x1400003e0d8}, {0x0?, 0x103d6d190?}, {0x104162900, 0x14000b56390}, {0x104149d60, 0x1400000e020}, 0x140005cc480)
      /home/runner/go/pkg/mod/github.com/moby/buildkit@v0.9.0/util/progress/progressui/display.go:62 +0x2ac
github.com/superfly/flyctl/internal/build/imgsrc.runBuildKitBuild.func4.1.3()
      /home/runner/work/flyctl/flyctl/internal/build/imgsrc/dockerfile_builder.go:403 +0x58
golang.org/x/sync/errgroup.(*Group).Go.func1()
      /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
      /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa0
```

**Comment by DAlperin** [comment]
Looks like we might need to pull in this patch https://github.com/tonistiigi/vt100/commit/f9a4f7ef65311848d4d4791c649a178c8e97386b

**Comment by tomr-a5** [comment]
The BuildKit upgrade in [#4758](https://github.com/superfly/flyctl/pull/4758) added a guard for terminals narrower than the progress display, so this now clamps the render width instead of panicking. I’m going to close this as fixed. Please reopen if the latest flyctl still crashes in a very narrow terminal.
