### ISSUE TITLE
segfault in cli on remote build failure

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#26]
```
Build complete - failed
==> Monitoring Deployment
You can detach the terminal anytime without stopping the deployment
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18f4a17]
goroutine 1 [running]:
github.com/superfly/flyctl/cmd.watchDeployment(0xc0003f5400, 0x0, 0x0)
        /github/workspace/cmd/deploy.go:168 +0x517
github.com/superfly/flyctl/cmd.runDeploy(0xc0003f5400, 0x0, 0x0)
        /github/workspace/cmd/deploy.go:99 +0x72e
github.com/superfly/flyctl/cmd.BuildCommand.func1(0xc00021cf00, 0x23d5820, 0x0, 0x0)
        /github/workspace/cmd/command.go:223 +0x172
github.com/spf13/cobra.(*Command).execute(0xc00021cf00, 0x23d5820, 0x0, 0x0, 0xc00021cf00, 0x23d5820)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x23acc80, 0xc00052bf20, 0x103b2ca, 0x235a340)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/superfly/flyctl/cmd.Execute()
        /github/workspace/cmd/root.go:34 +0x66
main.main()
        /github/workspace/main.go:6 +0x20
```

**Comment by michaeldwan** [comment]
fixed
