### ISSUE TITLE
`flyctl deploy` fails to push image

### ISSUE THREAD

**Issue by benja-M-1** [superfly/flyctl#3032]
*Please only report specific issues with `flyctl` behavior*. Anything like a support request for your application should go to https://community.fly.io. More people watch that space and can help you faster!

**Describe the bug**
Briefly, describe what broke and provide the following details:

I set up a very simple application and tried to deploy it but `flyctl deploy` failed with the following error

```
==> Pushing image to fly
The push refers to repository [registry.fly.io/wispy-darkness-7056]
Error: failed to fetch an image or build from source: error rendering push status stream: Get "https://registry.fly.io/v2/": dial tcp: lookup registry.fly.io on [fdaa::3]:53: server misbehaving
```

* Operating system
* `fly version`
```
❯ flyctl version
flyctl v0.1.121 darwin/arm64 Commit: 1f0fb69280a33483d0516b28606f0254c54d1721-dirty BuildDate: 2023-11-10T05:58:34Z
```

** Paste your `fly.toml`

```toml
app = "wispy-darkness-7056"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
```

** Command output: **

```text
❯ flyctl deploy --debug --verbose
==> Verifying app config
Validating /Users/benjamingrandfond/Dev/benjamin/tgtg-scanner/fly.toml
Platform: machines
✓ Configuration is valid
--> Verified app config
==> Building image
Remote builder fly-builder-dark-sun-5041 ready
==> Building image with Buildpacks
--> docker host: 20.10.12 linux x86_64
base: Pulling from paketobuildpacks/builder
Digest: sha256:17ea21162ba8c7717d3ead3ee3836a368aced7f02f2e59658e52029bd6d149e7
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:1af9935d8987fd52b2266d288200c9482d1dd5529860bbf5bc2d248de1cb1a38
Status: Image is up to date for paketobuildpacks/run:base-cnb
===> ANALYZING
Restoring data for SBOM from previous image
===> DETECTING
paketo-buildpacks/procfile 5.6.4
===> RESTORING
===> BUILDING

Paketo Buildpack for Procfile 5.6.4
  https://github.com/paketo-buildpacks/procfile
  Process types:
    web: gunicorn app:app
===> EXPORTING
Reusing layer 'buildpacksio/lifecycle:launch.sbom'
Reusing 1/1 app layer(s)
Reusing layer 'buildpacksio/lifecycle:launcher'
Reusing layer 'buildpacksio/lifecycle:config'
Reusing layer 'buildpacksio/lifecycle:process-types'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
Setting default process type 'web'
Saving registry.fly.io/wispy-darkness-7056:cache...
*** Images (7ed1efcab558):
      registry.fly.io/wispy-darkness-7056:cache
      registry.fly.io/wispy-darkness-7056:deployment-01HF793TT3N4NV40WBJ7ES2FVA
--> Building image done
==> Pushing image to fly
The push refers to repository [registry.fly.io/wispy-darkness-7056]
Error: failed to fetch an image or build from source: error rendering push status stream: Get "https://registry.fly.io/v2/": dial tcp: lookup registry.fly.io on [fdaa::3]:53: server misbehaving
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/superfly/flyctl/internal/cli.printError(0x14000132be0, 0x1400081dc1e, 0x1023c31e0?, {0x10277e0e8, 0x1400015dee0})
	github.com/superfly/flyctl/internal/cli/cli.go:148 +0x360
github.com/superfly/flyctl/internal/cli.Run({0x102799430?, 0x14000165b00?}, 0x14000132be0, {0x14000164050?, 0x3, 0x3})
	github.com/superfly/flyctl/internal/cli/cli.go:100 +0x7c0
main.run()
	github.com/superfly/flyctl/main.go:47 +0x174
main.main()
	github.com/superfly/flyctl/main.go:26 +0x20
```

**Comment by Roadmaster** [comment]
Hi, this is actually the remote builder having trouble contacting the registry. This was due to a DNS server in the `mia` region with stale data, it had to be reset to get DNS resolution working again.

This was not related to `flyctl` proper - it was just displaying the output from the troubled builder.

Thanks for reporting!

**Comment by benja-M-1** [comment]
I works now! Thanks @Roadmaster :)
