### ISSUE TITLE
Brew Install Fails (apple arm64)

### ISSUE THREAD

**Issue by pckilgore** [superfly/flyctl#366]
```console
(✓) 10:52:33 [~]
$ brew install superfly/tap/flyctl
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:253:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:206:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:138:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:138:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:290:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:351:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:648:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:644:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:644:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:301:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:132:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'

(✖ - 1) 10:52:40 [~]
$ brew --version
Homebrew 3.0.1
Homebrew/homebrew-core (git revision c81a0a; last commit 2021-02-19)
Homebrew/homebrew-cask (git revision f9d95f; last commit 2021-02-19)
```

**Comment by jeromegn** [comment]
We don't yet support it, unfortunately.

For now you can build it from source pretty easily.

We'll update this soon enough (I'm on a M1 Mac, so I am motivated).

**Comment by pckilgore** [comment]
Sorry, I was moving quickly I guess my edit didn't stick:  The shell script works fine, not a blocker, that Rosetta's (is that a verb now?) fine.

**Comment by jeromegn** [comment]
This should now be fixed!
