### ISSUE TITLE
`fly console` fails if `vm.memory` is set in fly.toml without `vm.cpu_kind` and `vm.cpus`

### ISSUE THREAD

**Issue by lesliebc** [superfly/flyctl#4107]
**Describe the bug**
`fly console` spits out "**Oops, something went wrong! Could you try that again?**" if:
- `vm.memory` is set alone in fly.toml, or
- `vm.memory` is set with `vm.size` only

This can be worked around by adding `vm.cpu_kind` and `vm.cpus`.

* `fly version`
fly v0.3.46 darwin/arm64 Commit: 65df1119742ce65d4ce99c71324702a61df5242a BuildDate: 2024-12-04T14:43:36Z
(also observed in releases since at least v0.3.42)

** Paste your `fly.toml`

```toml
app = 'myapp'
primary_region = 'ewr'
console_command = '/rails/bin/rails console'

# omitted other sections for brevity

[[vm]]
  memory = "2gb"
  size = "shared-cpu-4x"
```

** Command output: **
```
% fly console
Oops, something went wrong! Could you try that again?

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x64
github.com/superfly/flyctl/internal/sentry.printError({0x10478de40, 0x105e43ed0})
        github.com/superfly/flyctl/internal/sentry/sentry.go:190 +0x168
github.com/superfly/flyctl/internal/sentry.Recover({0x10478de40, 0x105e43ed0})
        github.com/superfly/flyctl/internal/sentry/sentry.go:180 +0xb8
main.run.func1()
        github.com/superfly/flyctl/main.go:40 +0x34
panic({0x10478de40?, 0x105e43ed0?})
        runtime/panic.go:785 +0x124
github.com/superfly/flyctl/internal/command/console.determineEphemeralConsoleMachineGuest({0x104b371a8, 0x14000939bf0}, 0x10402e747?)
        github.com/superfly/flyctl/internal/command/console/console.go:414 +0xb0
github.com/superfly/flyctl/internal/command/console.selectMachine({0x104b371a8, 0x14000939bf0}, 0x140006683f8, 0x140000b6b60)
        github.com/superfly/flyctl/internal/command/console/console.go:246 +0x68
github.com/superfly/flyctl/internal/command/console.runConsole({0x104b371a8, 0x14000666270})
        github.com/superfly/flyctl/internal/command/console/console.go:204 +0x378
github.com/superfly/flyctl/internal/command/console.New.New.newRunE.func1(0x140005f7808, {0x105efd0a0?, 0x4?, 0x104021416?})
        github.com/superfly/flyctl/internal/command/command.go:140 +0x188
github.com/spf13/cobra.(*Command).execute(0x140005f7808, {0x105efd0a0, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x14000032308)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
        github.com/spf13/cobra@v1.8.1/command.go:1050
github.com/superfly/flyctl/internal/cli.Run({0x104b37330?, 0x14000576900?}, 0x140006957c0, {0x140001dc070, 0x1, 0x1})
        github.com/superfly/flyctl/internal/cli/cli.go:94 +0x5a0
main.run()
        github.com/superfly/flyctl/main.go:47 +0x174
main.main()
        github.com/superfly/flyctl/main.go:26 +0x20
```

**Comment by knksmith57** [comment]
This bit us today. Thanks for providing a workaround, @lesliebc.

Here's what we had before (that worked fine) but now crashes `fly console`:

```toml
[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
```

And here's the workaround after adding `vm.cpus` and `vm.cpu_kind`:

```toml
[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
  cpus = 2
  cpu_kind = "shared"
```

[Per the docs](https://fly.io/docs/reference/configuration/#the-vm-section), all of these keys should be optional, so this is definitely broken in the current release and not user error.

I wonder if this breakage is at all related to @jipperinbham's [work to remove the global GraphQL API call dependency from configuration normalization](https://community.fly.io/t/theres-an-incident-affecting-the-machines-api-globally-every-week/22820/7?u=kyleatcausadix) 🤔

**Comment by dangra** [comment]
Hi guys, this bug was introduced in https://github.com/superfly/flyctl/pull/4073. It is not related to the GraphQL work.

A fix will be released soon https://github.com/superfly/flyctl/pull/4112

**Comment by knksmith57** [comment]
I'm on `0.3.50` and this is still a problem:

```
❯ fly version
fly v0.3.50 darwin/arm64 Commit: a9c2fb39a36edbff834da9d35704dd351203461b BuildDate: 2024-12-12T17:06:06Z
```

```
❯ fly console --select
Error: invalid CPU kind ''; valid values are 'shared' and 'performance'
```

```
❯ fly config show | jq .vm
[
  {
    "size": "shared-cpu-2x",
    "memory": "1gb"
  }
]
```

**Comment by knksmith57** [comment]
Cross-linking to #4049 for visibility

**Comment by dangra** [comment]
@knksmith57 you are right. I focused on ficing the panic and forgot to look at the original bug. Will try to craft a fix but can't promise it for this week 🏖️
