### ISSUE TITLE
`flyctl postgres db list appname` segfaults

### ISSUE THREAD

**Issue by Qqwy** [superfly/flyctl#597]
**Describe the bug**

When running 

```
flyctl postgres db list your_app_name
```

** Command output: **

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7169d4]

goroutine 1 [running]:
github.com/superfly/flyctl/api.(*Client).ListPostgresDatabases(0x40ccb4, {0x7ffda272fb2f, 0x5})
        /home/runner/work/flyctl/flyctl/api/resource_postgres.go:129 +0x1f4
github.com/superfly/flyctl/cmd.runListPostgresDatabases(0xc00046b080)
        /home/runner/work/flyctl/flyctl/cmd/postgres.go:241 +0x4c
github.com/superfly/flyctl/cmd.BuildCommandCobra.func1(0xc00043d180, {0xc0004e9c50, 0x1, 0x1})
        /home/runner/work/flyctl/flyctl/cmd/command.go:214 +0x19d
github.com/spf13/cobra.(*Command).execute(0xc00043d180, {0xc0004e9c30, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000140000)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:911
main.run()
        /home/runner/work/flyctl/flyctl/main.go:46 +0x12a
main.main()
        /home/runner/work/flyctl/flyctl/main.go:25 +0x45
```

I'm pretty sure this has to do with a discrepancy between the documentation, the `help` text and what the cli tool really expects:

- [The documentation](https://fly.io/docs/reference/postgres/#listing-databases) mentions `flyctl postgres databases list`
- When running this command using `flyctl`, an error page is shown stating that `postgres` does not accept `databases` but does accept, amongst other possibilities, `db`.
- When running `flyctl postgres db list` again an error page is shown, stating that an argument is expected
- When passing as argument either the main app name or the name of a postgres database in the app, above segfault occurs.

_(Flyctl version string: `flyctl v0.0.250 linux/amd64 Commit: 7a90db9 BuildDate: 2021-10-28T20:49:47Z`)_

**Comment by davissp14** [comment]
@Qqwy Would you mind updating flyctl to version `v0.0.270` and trying this again?

**Comment by Qqwy** [comment]
Yes!

```
bash $ flyctl postgres databases list
Manage postgres clusters

Usage:
  flyctl postgres [command]

Aliases:
  postgres, pg

Available Commands:
  attach      Attach a postgres cluster to an app
  connect     Connect to postgres cluster
  create      Create a postgres cluster
  db          manage databases in a cluster
  detach      Detach a postgres cluster from an app
  list        list postgres clusters
  users       manage users in a cluster

Flags:
  -h, --help   help for postgres

Global Flags:
  -t, --access-token string   Fly API Access Token
  -j, --json                  json output
      --verbose               verbose output

Use "flyctl postgres [command] --help" for more information about a command.
bash $ flyctl postgres db list
Error: accepts 1 arg(s), received 0
Usage:
  flyctl postgres db list <postgres-cluster-name> [flags]

Flags:
  -a, --app string      App name to operate on
  -c, --config string   Path to an app config file or directory containing one (default "./fly.toml")
  -h, --help            help for list

Global Flags:
  -t, --access-token string   Fly API Access Token
  -j, --json                  json output
      --verbose               verbose output

Error accepts 1 arg(s), received 0


bash $ flyctl postgres db list oberx
Running flyadmin database-list
Error unexpected end of JSON input


bash $ flyctl postgres db list oberx-prod-db
WARN app flag 'oberx-prod-db' does not match app name in config file 'oberx'
? Continue using 'oberx-prod-db' Yes
Running flyadmin database-list
NAME     USERS                                               
oberx    flypgadmin,oberx_wg75m6r3ee6lzjy2,postgres,repluser 
postgres flypgadmin,oberx_wg75m6r3ee6lzjy2,postgres,repluser 
```

So it seems to work correctly when passing the name of the postgres cluster, and no longer segfaults. 
However, output still feels a bit counter-intuitive as you need to run it with the postgres cluster name and the command tries to strongly suggest to you that you should use your app's name instead.

And if we do, we get a JSON parser error, rather the command telling us that we should try with the postgres cluster name.
