### ISSUE TITLE
Some log lines from the release task are dropped

### ISSUE THREAD

**Issue by sudhirj** [superfly/flyctl#604]
This output during `fly deploy` has a few lines missing:
```
==> Release command
Command: /bin/rake db:migrate
	 Starting instance
	 Configuring virtual machine
	 Pulling container image
	 Unpacking image
	 Preparing kernel init
	 Configuring firecracker
	 Starting virtual machine
	 Starting init (commit: 7943db6)...
	 Preparing to run: `launcher /bin/rake db:migrate` as heroku
	 2021/11/12 18:42:19 listening on [fdaa:0:38f8:a7b:f0f:987d:a2cf:2]:22 (DNS: [fdaa::3]:53)
	 rake aborted!
	 /workspace/Rakefile:6:in `require_relative'
	 /workspace/Rakefile:6:in `<top (required)>'
	 (See full trace by running task with --trace)
	 Stin child exited normally with code: 1
	 Starting clean up.
Error Release command failed, deployment aborted
```

The missing lines are in the `fly logs`:
```
2021-11-12T18:42:03.484 runner[987da2cf] sin [info] Starting instance
2021-11-12T18:42:03.511 runner[987da2cf] sin [info] Configuring virtual machine
2021-11-12T18:42:03.512 runner[987da2cf] sin [info] Pulling container image
2021-11-12T18:42:13.548 runner[987da2cf] sin [info] Unpacking image
2021-11-12T18:42:18.655 runner[987da2cf] sin [info] Preparing kernel init
2021-11-12T18:42:19.053 runner[987da2cf] sin [info] Configuring firecracker
2021-11-12T18:42:19.053 runner[987da2cf] sin [info] Starting virtual machine
2021-11-12T18:42:19.217 app[987da2cf] sin [info] Starting init (commit: 7943db6)...
2021-11-12T18:42:19.234 app[987da2cf] sin [info] Preparing to run: `launcher /bin/rake db:migrate` as heroku
2021-11-12T18:42:19.249 app[987da2cf] sin [info] 2021/11/12 18:42:19 listening on [fdaa:0:38f8:a7b:f0f:987d:a2cf:2]:22 (DNS: [fdaa::3]:53)
2021-11-12T18:42:19.584 app[987da2cf] sin [info] rake aborted!
2021-11-12T18:42:19.584 app[987da2cf] sin [info] Bundler::RubyVersionMismatch: Your Ruby version is 2.7.0, but your Gemfile specified 3.0.2
2021-11-12T18:42:19.584 app[987da2cf] sin [info] /workspace/config/boot.rb:5:in `<top (required)>'
2021-11-12T18:42:19.584 app[987da2cf] sin [info] /workspace/config/application.rb:3:in `require_relative'
2021-11-12T18:42:19.584 app[987da2cf] sin [info] /workspace/config/application.rb:3:in `<top (required)>'
2021-11-12T18:42:19.584 app[987da2cf] sin [info] /workspace/Rakefile:6:in `require_relative'
2021-11-12T18:42:19.584 app[987da2cf] sin [info] /workspace/Rakefile:6:in `<top (required)>'
2021-11-12T18:42:19.584 app[987da2cf] sin [info] /layers/heroku_ruby/gems/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
2021-11-12T18:42:19.584 app[987da2cf] sin [info] (See full trace by running task with --trace)
2021-11-12T18:42:20.242 app[987da2cf] sin [info] Stin child exited normally with code: 1
2021-11-12T18:42:20.242 app[987da2cf] sin [info] Starting clean up.
```

The `2021-11-12T18:42:19.584 app[987da2cf] sin [info] Bundler::RubyVersionMismatch: Your Ruby version is 2.7.0, but your Gemfile specified 3.0.2` and the next one didn't come through, and they're the actual error. 

Running `fly v0.0.252 darwin/arm64 Commit: 8e42f89 BuildDate: 2021-11-10T20:46:26Z`

**Comment by jsierles** [comment]
Is this still happening?

**Comment by sudhirj** [comment]
Not that I've noticed recently.

**Comment by michaeldwan** [comment]
Solved in apps v2
